language: c

os: linux

dist: bionic

compiler:
  - gcc

before_script:
# Setup cmake build
  - mkdir build
  - cd build
  - cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Debug -G "Unix Makefiles" ..

script:
  - make